# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vikas1994
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test-demo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: nationality-ip
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: handler.handler
    events:
      - httpApi: "*"
